name: Build and Push Docs Container

on:
  push:
    paths:
      - "environment.yml"
      - ".github/docker/Dockerfile"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docs-container:latest
