name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install .
      - name: Download data release from Zenodo
        run: |
          curl --progress-bar \
               -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
               -L \
               -o data_release/gw_smc_data_release_results.zip \
               https://zenodo.org/api/files/70280df5-4205-4726-ba71-b70ff2b29dfa/gw_smc_data_release_results.zip
          mkdir p data_release/gw_smc_data_release_data/
          curl --progress-bar \
               -H "Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}" \
               -L \
               -o data_release/gw_smc_data_release_data.zip \
               https://zenodo.org/api/files/70280df5-4205-4726-ba71-b70ff2b29dfa/gw_smc_data_release_data.zip
      - name: Unzip data release
        run: |
            unzip -o data_release/gw_smc_data_release_results.zip -d data_release
            unzip -o data_release/gw_smc_data_release_data.zip -d data_release/gw_smc_data_release_data/
            ls data_release/gw_smc_data_release_results/
            ls data_release/gw_smc_data_release_data/
      - name: Build the book
        run: |
          cd docs
          make build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
